Repository COALA-OJ/7Nights_game, pull requests merged in 2021-01, with the labels that each got.

#42 Update process of Player movement Feature/#39
  7Nights_react.py
Labels: react

#43 Feature/#11
  7Nights_react.py
Labels: react

#26 create where_st_pos.py
  where_st_pos.py
Labels: spring

#41 create random_making_mob.py
  random_making_mob.py
Labels: flask

#45 Feature/#21
  get_mosterid.py
Labels: flask

#49 getmonster_dmg.py
  getmonster_dmg#14.py
Labels: flask

#46 getmonster_hp.py
  getmonster_hp.py
Labels: flask

#47 save_map_info.py
  save_map_info.py
Labels: flask

#50 Feature/#2
  is_map_only_zero.py
Labels: spring

#51 Feature/#1
  init_map.py
Labels: spring

#34 create can_conq.py
  can_conq.py
Labels: spring

#35 create get_mob_loc.py
  get_mob_loc.py
Labels: spring

#63 create water.png & monster2.png
  Image/monster2.png
  Image/water.png
Labels: react

#64 create grass.png
  grass.png
Labels: react

#69 create reset.py
  reset.py
Labels: flask

#84 make_new_st_pos.py
  make_new_st_pos.py
Labels: spring

#86 Create renew_mob_info.py
  renew_mob_info.py
Labels: spring

#75 create get_item
  get_item.py
Labels: flask

#76 create user_info_update.py
  user_info_update.py
Labels: flask

#71 modify some return value
  result_update.py
Labels: flask
